apiVersion: v1
kind: Namespace
metadata:
  name: multinic-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: multinic-operator
  name: multinic-controller
  labels:
    project.name: multinic-controller
    project.app: multinic-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multinic-controller
  labels:
    project.app: multinic-controller
    project.name: multinic-controller
rules:
  - apiGroups:
    - 'vmoperator.vmware.com'
    resources:
    - 'virtualmachines'
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: multinic-controller
  labels:
    project.app: multinic-controller
    project.name: multinic-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: multinic-controller
subjects:
- kind: ServiceAccount
  name: multinic-controller
  namespace: multinic-operator
---
apiVersion: v1
kind: Secret
metadata:
  namespace: multinic-operator
  name: vcenter-secret
  labels:
    project.app: multinic-controller
    project.name: multinic-controller
type: Opaque
data:
  vcenter-password: Vk13QHJlMTIzCg==
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: multinic-operator
  name: vcenter-config
  labels:
    project.app: multinic-controller
    project.name: multinic-controller
data:
  vcenter-url: "192.168.100.50"
  vcenter-login-id: "testuser@vsphere.local"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: multinic-operator
  labels:
    project.name: multinic-controller
    project.app: multinic-controller
  name: multinic-controller
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      project.app: multinic-controller
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        project.app: multinic-controller
    spec:
      containers:
      - name: multinic-controller 
        image: us-central1-docker.pkg.dev/navneet-410819/whoami6443-hub/whoami6443/multi-nic-controller:0.0.4
        env:
        - name: GOVMOMI_HOME
          value: "/tmp"
        - name: GOVC_INSECURE
          value: "1"
        - name: GOVC_URL
          valueFrom:
            configMapKeyRef:
              name: vcenter-config
              key: vcenter-url
        - name: GOVC_USERNAME
          valueFrom:
            configMapKeyRef:
              name: vcenter-config
              key: vcenter-login-id
        - name: GOVC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vcenter-secret
              key: vcenter-password
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          privileged: false
          runAsNonRoot: true
          runAsUser: 9999
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        stdin: true
        tty: true
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: CRX
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: multinic-controller
      serviceAccountName: multinic-controller
      terminationGracePeriodSeconds: 30
      volumes:
      - name: tmp-volume
        emptyDir: {}